WDP190102-13
kodilla-wdp-group-project/WDP-1901-02 pull request #11
Opened 2019-02-11 08:15 UTC by pav1984

Ten task dotyczy kart korzyści ("Free shipping", etc.).
Klient chce w trybach tablet i mobile mieć je w 2 rzędach, po 2 elementy w każdym, ale elementy w jednym rzędzie (obok siebie) nie powinny się różnić wysokością.

2019-02-11 08:34 UTC, Varenthein approved these changes

2019-02-12 22:16 UTC, hul approved these changes

2019-02-12 22:28 UTC, hul requested changes
Sekcja z kartami korzyści jest teraz rozjechana:
https://www.dropbox.com/s/rxieb2g34juit5h/Screen%20Shot%202019-02-12%20at%2023.26.16.png?dl=0
https://www.dropbox.com/s/geymorqw36ptne9/Screen%20Shot%202019-02-12%20at%2023.26.33.png?dl=0
Trzeba poprawić kod html.

2019-02-13 07:12 UTC, pav1984 commented
Witam. Chcę bardzo poprawić ten błąd i z rzutu ekranu widzę że w złym miejscu jest domknięcie div ,ale u mnie jest wszystko ok.
![zrzut ekranu 2019-02-13 o 08 01 29](https://user-images.githubusercontent.com/44226885/52693298-a4d36d80-2f66-11e9-9ecb-075a47d62942.png)
![zrzut ekranu 2019-02-13 o 08 09 45](https://user-images.githubusercontent.com/44226885/52693351-ce8c9480-2f66-11e9-9ae5-de37375fc8fc.png)

2019-02-13 11:18 UTC, pav1984 commented
Dobrze znalazłem problem myśle, że teraz będzie okej :) nie wiem skąd się wziął znacznik </a> zamiast </div> jakiś chochlik pewnie:)

2019-02-15 12:50 UTC, karolinaszczurek approved these changes

2019-02-18 18:09 UTC, hul approved these changes

2019-02-19 06:11 UTC, merged