WDP190102-5
kodilla-wdp-group-project/WDP-1901-02 pull request #13
Opened 2019-02-11 08:36 UTC by pav1984

Brak ostylowanych stanów "ulubiony" oraz "dodany do porównania". Te stany mogą być dodane na stałe poprzez dodanie klasy "active" na buttonie.
W podglądzie projektu musi być co najmniej po jednym produkcie, który ma klasy active:

* na żadnym z tych buttonów
* tylko na "ulubiony"
* tylko na "dodany do porównania"
* na obu buttonach

2019-02-12 22:41 UTC, hul requested changes

2019-02-12 22:41 UTC, hul commented on src/partials/50_section-products.html
> +                ><i class="fas fa-exchange-alt"></i
Tu popsuło się formatowanie...

2019-02-12 22:41 UTC, hul commented on src/partials/50_section-products.html
> +                ><i class="fas fa-exchange-alt"></i
Tu też popsuło się formatowanie...

2019-02-12 22:41 UTC, hul commented on src/sass/components/_button.scss
> +    color: #ffffff;
Kolor polecam zdefiniować w _variables

2019-02-18 18:13 UTC, hul approved these changes

2019-02-19 18:51 UTC, Varenthein requested changes
Rozwiąż proszę konflikty

2019-02-19 18:52 UTC, Varenthein requested changes
Rozwiąż proszę konflikty

2019-02-20 06:13 UTC, pav1984 commented
Rozwiązany.

2019-02-20 19:51 UTC, RederAc3 requested changes

2019-02-20 19:51 UTC, RederAc3 commented on src/partials/50_section-products.html
> +              <a href="#" class="btn-outline active"><i class="fasfa-exchange-alt"></i></a>
Popraw klasy bo nie wyświetla się ikonka na stronie

2019-02-21 06:32 UTC, pav1984 commented
Dzięki juz poprawiłem.

2019-02-21 06:43 UTC, RederAc3 approved these changes

2019-02-23 20:20 UTC, karolinaszczurek approved these changes

2019-02-24 16:45 UTC, Varenthein approved these changes

2019-02-24 16:45 UTC, merged