Wdp190102-30
kodilla-wdp-group-project/WDP-1901-02 pull request #15
Opened 2019-02-12 21:39 UTC by karolinaszczurek

@hul 

Dodany slider na sekcji brands. Tu za pomocą bootstrapa, wersja RWD będzie już na tiny-slider, ale to na innym branchu :)

2019-02-12 22:31 UTC, hul approved these changes

2019-02-13 12:06 UTC, pav1984 commented on src/partials/section-brands.html
> +    <div class="carousel-inner">
Tutaj popsuło się formatowanie...

2019-02-13 12:07 UTC, pav1984 commented on src/partials/section-brands.html
> +      </a>
Tutaj popsuło się formatowanie...

2019-02-13 12:07 UTC, pav1984 commented on src/partials/section-brands.html
> +    </div>
Tutaj popsuło się formatowanie...

2019-02-13 12:09 UTC, pav1984 requested changes
Wszystko dobrze 👍 Proszę popraw tylko formatowanie w Html

2019-02-15 12:46 UTC, pav1984 approved these changes

2019-02-20 18:46 UTC, RederAc3 approved these changes

2019-02-23 19:43 UTC, merged