Wdp190102-31
kodilla-wdp-group-project/WDP-1901-02 pull request #16
Opened 2019-02-12 21:44 UTC by karolinaszczurek

Dodane RWD do slidera w sekcji brands, z wykorzystaniem tiny-slider.

2019-02-12 22:36 UTC, hul approved these changes

2019-02-13 11:44 UTC, pav1984 requested changes
Witam. Bardzo fajne wykonanie, ale mam sugestię czy na telefonach nie byłoby lepiej zrobić tak, żeby wyświetlało się 1 zdjęcie? teraz też jest okej, ale zdjęcia trochę za bardzo są przyklejone do strzałek zmieniających slajd. Za zadanie dałbym 'Approve' ,ale proszę rozwiąż konflikt 👍

2019-02-15 11:34 UTC, karolinaszczurek commented
@pav1984  konflikt rozwiązany

2019-02-15 12:58 UTC, pav1984 approved these changes

2019-02-23 19:50 UTC, merged