WDP190102-14
kodilla-wdp-group-project/WDP-1901-02 pull request #17
Opened 2019-02-13 12:16 UTC by pav1984

Ten task dotyczy sekcji "New furniture".
Klient chciałby na tabletach mieć po 2-3 elementy w rzędzie, a na mobilkach 1-2 w rzędzie. Są zakresy, bo trzeba będzie samodzielnie zdecydować co wygląda ok - np. na tabletach landscape (np. szer. 1024px) mogą być 3, a na portrait (np. szer. 768px) by były 2. Podobnie na mobilkach, na takich koło 568px by były 2, a na mniejszych 1 w rzędzie.
Docelowo to będzie slider, więc będzie widoczny tylko 1 wiersz

2019-02-15 12:29 UTC, karolinaszczurek reviewed
Dlaczego RWD jest dodane tylko na pierwszych 4 oknach? :)
Czy to specjalnie, ze względu na zapis "Docelowo to będzie slider, więc będzie widoczny tylko 1 wiersz"?

I linia 53 - chyba masz literówkę "ccol-sm-12"

2019-02-15 13:18 UTC, pav1984 commented
Dzięki. Już poprawiłem 👍

2019-02-18 08:39 UTC, Varenthein requested changes
Jeśli to zadania tyczy się całej sekcji New Furtniture, to warto pomyśleć o nadaniu jakiejś responsywności dla menu ("Bed", "Chair" itd.), bo jednak nie wygląa to w tej chwili za dobrze.

2019-02-18 11:36 UTC, pav1984 commented
Dodałem responywność.

2019-02-18 18:26 UTC, hul approved these changes

2019-02-19 18:53 UTC, Varenthein approved these changes

2019-02-19 18:53 UTC, merged