WDP190102-24
kodilla-wdp-group-project/WDP-1901-02 pull request #18
Opened 2019-02-13 12:18 UTC by pav1984

Na stronie należy dodać sekcję "Promocje" według designu:
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-deals.png
Jest to zwykła statyczna sekcja (HTML i CSS). Wszystkie 3 boxy powinny być stałej wysokości.

2019-02-18 20:26 UTC, przemo88 approved these changes
Zgodnie z treścią zadania.

2019-02-19 18:58 UTC, Varenthein requested changes
Po co używać pozycji absolutnej do takich prostych układów? Mogłeś spokojnie osiągnąć te same efekty za pomocą flexa. Flex zawsze jest bezpieczniejszy, nie tak sztywny jak `position: absolute`.

2019-02-20 13:04 UTC, pav1984 commented
Popraweiłem 👍

2019-02-20 15:30 UTC, RederAc3 approved these changes
Wszystko ok ale jak by połączyć wspólne style klasy .special-container, .special-header i .sale-container to co mają wspólnego to razem i zamiast kilka linijek background-image, size ,repeat zastosować samo background? mniej kodu i bez powtarzania

2019-02-20 21:46 UTC, hul approved these changes

2019-02-24 16:46 UTC, Varenthein approved these changes

2019-02-24 16:47 UTC, merged