WDP190102-19
kodilla-wdp-group-project/WDP-1901-02 pull request #20
Opened 2019-02-14 08:08 UTC by pav1984

Trzeba napisać JS do gwiazdek. Nie używamy żadnego pluginu, piszemy własny skrypt do tego. 
Więcej szczegółów tutaj https://projects.kodilla.com/browse/WDP190102-19

2019-02-14 20:19 UTC, RederAc3 requested changes
Ładnie to wygląda tylko że przy kliknięciu w coś na stronie, text czy nawet gwiazdki pokazuje się mrugający kursor a kliknięcie pomiędzy gwiazdki zaznacza wszystkie.

2019-02-15 13:23 UTC, pav1984 commented
Dzięki. Myśle że teraz jest ok.

2019-02-18 20:15 UTC, przemo88 approved these changes
Wszystko w porządku.

2019-02-18 20:48 UTC, hul approved these changes

2019-02-20 15:20 UTC, RederAc3 approved these changes

2019-02-21 08:10 UTC, merged