WDP190102-2
kodilla-wdp-group-project/WDP-1901-02 pull request #4
Opened 2019-02-07 06:14 UTC by pav1984

Przy wyświetlaniu większej liczby np. 123 element Ilość produktów w koszyku nie zachowuje się jak trzeba. Poprawić tak, aby pozwalał na wyświetlanie liczb z zakresu 0-99999 (max. 5 cyfr).

2019-02-08 12:07 UTC, Varenthein approved these changes
Jest w porządku, ale rozwiąż konflikty proszę.

2019-02-08 12:08 UTC, Varenthein requested changes
Jest w porządku, ale rozwiąż konflikty proszę.

2019-02-08 15:32 UTC, pav1984 commented
Konflikty poprawione.

2019-02-08 15:46 UTC, Varenthein approved these changes

2019-02-10 20:31 UTC, hul approved these changes

2019-02-11 08:04 UTC, merged