WDP190102-1
kodilla-wdp-group-project/WDP-1901-02 pull request #7
Opened 2019-02-07 16:36 UTC by karolinaszczurek

@hul @tvardy   Dodane zdjęcia do sekcji 'new furniture' i 'blog posts'.

2019-02-10 20:55 UTC, hul requested changes

2019-02-10 20:55 UTC, hul commented on src/partials/70_section-blog-posts.html
> +          <a href="#">
Element **a** zawierający cover'a jest nadmiarowy. Widać to szczególnie na kolejnych przykładach, gdzie mamy **a** zawierający child'a **a** (Read more). Generalnie jak coś jest **a** to nie może zawierać klikalnych childów.

Usuń **a** wyższego poziomu.

2019-02-10 20:55 UTC, hul commented on src/sass/components/_post-box.scss
> +    ////background: {
Komentarze do sprzątnięcia to i tam...

2019-02-10 21:04 UTC, hul commented
Obrazki są OK, ale tych commitów nie powinno być w tym pull requeście: 
 - Update recent blog section - add hovers
 - Update _post-box.scss - details hover
Poczekaj z mergem pull requesta aż zostaną zmergowane te poprzednie.

2019-02-15 11:49 UTC, karolinaszczurek commented
@hul Rozwiązałam konflikt, usunęłam komentarze.

2019-02-18 18:07 UTC, hul commented
@karolinaszczurek w src/sass/components/_post-box.scss jednak coś z zakomentowago kodu zostało...

2019-02-18 19:17 UTC, karolinaszczurek commented
@hul Komentarze usunięte.
Dzięki!

2019-02-20 21:44 UTC, hul approved these changes
Jeszcze konflikty i będzie ok :)

2019-02-20 22:09 UTC, karolinaszczurek commented
@hul Konflikty usunięte :)

2019-02-23 21:41 UTC, hul approved these changes

2019-02-25 20:16 UTC, karolinaszczurek commented
@thisisui @mateuszwrobel @OskarLebuda @RederAc3 @pav1984 proszę o code review :)

2019-03-03 10:47 UTC, merged