WDP190102-8
kodilla-wdp-group-project/WDP-1901-02 pull request #8
Opened 2019-02-07 16:38 UTC by karolinaszczurek

@hul  Dodane hovery na sekcji posty bloga

2019-02-10 21:06 UTC, hul requested changes

2019-02-10 21:06 UTC, hul commented on src/partials/70_section-blog-posts.html
> +          <a href="#">
Opisałem temat tu:
https://github.com/kodilla-wdp-group-project/WDP-1901-02/pull/7#discussion_r255355263

2019-02-12 21:07 UTC, karolinaszczurek commented on src/partials/70_section-blog-posts.html
> +          <a href="#">
@hul 
@tvardy 
naniosłam poprawki.

2019-02-12 22:09 UTC, hul approved these changes

2019-02-13 22:46 UTC, Varenthein requested changes
Rozwiąż konflikty, żeby był możliwy merge.

2019-02-14 09:25 UTC, karolinaszczurek commented
Rozwiązałam konflikt.

2019-02-18 08:24 UTC, Varenthein approved these changes

2019-02-18 08:24 UTC, merged